######################################################################
# Automatically generated by qmake (2.01a) ons jul 8 13:55:52 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += communicate.h
SOURCES += communicate.cpp main.cpp
